FROM node:14.16.0-alpine
RUN apk add --no-cache --virtual .build-deps alpine-sdk python3
RUN mkdir -p /var/www/notification
WORKDIR /var/www/notification
ADD . /var/www/notification
RUN npm install
CMD npm run prod